import test from 'node:test'
import assert from 'node:assert/strict'
import {mergePortalEvidence,graphRelationships} from '../lib/portal-ecosystem.js'
const base={organizations:[{id:'org-funder',name:'Funder',website:'https://funder.test/',publicEmails:[]}],relationships:[],financing:[],dashboard:[]}
const orgs=[{id:'org-funder',name:'Funder',slug:'funder',tags:[]},{id:'venture',name:'Venture',slug:'venture',tags:['LifeTech','Venture']}]
const record={id:'support:one',record_id:'one',record_type:'organization_support',status:'reported',transaction_type:'acceleration',from_organization_id:'org-funder',to_organization_id:'venture',from_label:'Funder',to_label:'Venture',amount:null,source_url:'https://funder.test/cohort',description:'Cohort',notes:'',evidence:'Named participant'}
test('cohort relationships appear in full map and never become money',()=>{const data=mergePortalEvidence(base,orgs,[record,record]);assert.equal(data.relationships.length,1);assert.equal(graphRelationships(data).length,1);assert.equal(graphRelationships(data,{moneyOnly:true}).length,0);assert.equal(data.organizations[1].proximity,null);assert.equal(data.financing.length,0)})
test('refresh is idempotent and voided evidence is removed',()=>{const first=mergePortalEvidence(base,orgs,[record]);const second=mergePortalEvidence(first,orgs,[record]);assert.equal(second.relationships.length,1);assert.equal(mergePortalEvidence(second,orgs,[{...record,status:'voided'}]).relationships.length,0)})
test('awards preserve reported status and amounts; capitalizations are opt-in',()=>{const data=mergePortalEvidence(base,orgs,[{...record,transaction_type:'transfer',amount:4000,currency:'USD'},{...record,id:'support:capital',record_id:'capital',transaction_type:'capitalization'}]);assert.equal(graphRelationships(data,{moneyOnly:true}).length,1);assert.equal(graphRelationships(data,{moneyOnly:true,includeCapitalization:true}).length,2);assert.equal(data.financing[0].status,'reported');assert.equal(data.financing[0].amount,4000)})
test('imported workbook records are not duplicated and unsafe evidence is omitted',()=>{const data=mergePortalEvidence(base,orgs,[{...record,record_id:'bmoremedtech:existing'},{...record,source_url:'javascript:alert(1)'}]);assert.equal(data.relationships.length,1);assert.equal(data.relationships[0].sourceUrl,'')})
